/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.tw.control.Connect;
import com.tw.model.Items;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tw
 */
public class twclient extends javax.swing.JFrame {

    /**
     * Creates new form twclient
     */
    private String link = "https://opskins.com/index.php?search_item=__%25&min=75&max=77&grade=Grade&type=Type&sort=hl&StatTrak=1&loc=shop_search";
    private int tempo = 15;
    private float dollarhj = 3.13f;
    private float lucrominimo = 100;
    String p1 = "https://opskins.com/index.php?loc=shop_search&search_item=__%25&min=";
    String p2 = "500";
    String p3 = "&max=";
    String p4 = "1500";
    String p5 = "&";
    String p6 = "StatTrak=1";
    String p7 = "inline=&grade=&inline=&type=&inline=&sort=hl";

    public twclient() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);

        jftdollar.setText(dollarhj + "");
        jllinkurl.setText(link);

    }

    private void atualizalista(ArrayList<Items> items) {
        DefaultTableModel tabela = (DefaultTableModel) this.tabelatwclient.getModel();// não vindo a lista =/
        tabela.setRowCount(items.size());
        //System.out.println("Size items = "+items.size());

        int x = 0;
        for (Items it : items) {
            tabela.setValueAt(it.getNome(), x, 0);
            tabela.setValueAt(it.getLink(), x, 1);
            tabela.setValueAt(it.getSop(), x, 2);
            tabela.setValueAt(it.getSugerido(), x, 3);
            tabela.setValueAt(it.getLucroop(), x, 4);
            tabela.setValueAt(it.getLucroreais(), x, 5);

            /*System.out.println(x+"\nNome: " + it.getNome()
             + "\nLink: " + it.getLink()
             + "\n$Op: " + it.getSop()
             + "\nSugerido: " + it.getSugerido()
             + "\nLucro $Op: "+ it.getLucroop()
             + "\nLucro R$: " +it.getLucroreais()
             + "\nDollar: "+it.getDollaratual()
             + "\n\n");*/
            x++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelatwclient = new javax.swing.JTable();
        jftdollar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbuttonSimularHtml = new javax.swing.JButton();
        jbConnectOpskins = new javax.swing.JButton();
        jllinkurl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jftlucro = new javax.swing.JTextField();
        CheckBoxStatTrak = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        textfieldMax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textfieldMin = new javax.swing.JTextField();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TwClient");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelatwclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Link", "$Op", "Sugerido", "Lucro $Op", "Lucro $RS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelatwclient.setColumnSelectionAllowed(true);
        tabelatwclient.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelatwclient);
        tabelatwclient.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jftdollar.setText("3,13");
        jftdollar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftdollarMouseClicked(evt);
            }
        });
        jftdollar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftdollarActionPerformed(evt);
            }
        });

        jLabel1.setText("Dollar =");

        jbuttonSimularHtml.setText("Simular html");
        jbuttonSimularHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSimularHtmlActionPerformed(evt);
            }
        });

        jbConnectOpskins.setText("Connect Opskins");
        jbConnectOpskins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConnectOpskinsActionPerformed(evt);
            }
        });

        jllinkurl.setText("Link");

        jLabel2.setText("Steam 14%");

        jLabel3.setText("Opskins 10%");

        jLabel4.setText("Lucro R$:");

        jftlucro.setText("200");
        jftlucro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftlucroMouseClicked(evt);
            }
        });
        jftlucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftlucroActionPerformed(evt);
            }
        });

        CheckBoxStatTrak.setText("StatTrak");

        jLabel5.setText("Max");

        textfieldMax.setText("1500");

        jLabel6.setText("Min");

        textfieldMin.setText("500");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConnectOpskins)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonSimularHtml))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jllinkurl, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jftlucro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftdollar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(CheckBoxStatTrak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldMin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxStatTrak)
                    .addComponent(jLabel5)
                    .addComponent(textfieldMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textfieldMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jllinkurl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jftlucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jftdollar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jbuttonSimularHtml)
                    .addComponent(jbConnectOpskins)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jftdollarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftdollarActionPerformed

    }//GEN-LAST:event_jftdollarActionPerformed

    private void jbuttonSimularHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSimularHtmlActionPerformed

        p2 = textfieldMin.getText();
        p4 = textfieldMax.getText();
        if (CheckBoxStatTrak.isSelected()) {
            p6 = "StatTrak=1";
        } else {
            p6 = "";
        }
        link = p1 + p2 + p3 + p4 + p5 + p6 + p7;

        Connect con = new Connect();
        atualizalista((ArrayList<Items>) con.usetxt(dollarhj, lucrominimo));

    }//GEN-LAST:event_jbuttonSimularHtmlActionPerformed

    private void jbConnectOpskinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConnectOpskinsActionPerformed

        p2 = textfieldMin.getText();
        p4 = textfieldMax.getText();
        if (CheckBoxStatTrak.isSelected()) {
            p6 = "StatTrak=1";
        } else {
            p6 = "";
        }
        link = p1 + p2 + p3 + p4 + p5 + p6 + p7;

        if (link == null | link.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Você precisa colocar uma url válida");
        } else {
            Connect con = new Connect();
            atualizalista((ArrayList<Items>) con.connect(link, dollarhj, lucrominimo));
        }
    }//GEN-LAST:event_jbConnectOpskinsActionPerformed

    private void jftdollarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftdollarMouseClicked

        try {
            dollarhj = Float.parseFloat(JOptionPane.showInputDialog("Informe o valor do dolar atual x.xx"));
            jftdollar.setText(dollarhj + "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você precisa informar um valor válido ex: 3.13");
        }
    }//GEN-LAST:event_jftdollarMouseClicked

    private void jftlucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftlucroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftlucroActionPerformed

    private void jftlucroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftlucroMouseClicked

        try {
            lucrominimo = Float.parseFloat(JOptionPane.showInputDialog("Informe um lucro minimo."));
            jftlucro.setText(lucrominimo + "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Você precisa informar um valor válido ex: 3.13");
        }
    }//GEN-LAST:event_jftlucroMouseClicked

    /**
     *
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxStatTrak;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbConnectOpskins;
    private javax.swing.JButton jbuttonSimularHtml;
    private javax.swing.JTextField jftdollar;
    private javax.swing.JTextField jftlucro;
    private javax.swing.JLabel jllinkurl;
    private javax.swing.JTable tabelatwclient;
    private javax.swing.JTextField textfieldMax;
    private javax.swing.JTextField textfieldMin;
    // End of variables declaration//GEN-END:variables

}
